'use client';

import { useEffect, useState } from 'react';
import { supabase } from '@/lib/supabase';

interface DomainValuation {
  estimated_value_range: string;
  key_strengths: string[];
  potential_use_cases: string[];
  monetization_opportunities: string[];
  competitive_advantages: string[];
  improvement_recommendations: string[];
  market_analysis: string;
  full_report: string;
  generated_at: string;
}

export default function DomainValuation({ domain = 'wikithat.com' }: { domain?: string }) {
  const [valuation, setValuation] = useState<DomainValuation | null>(null);
  const [loading, setLoading] = useState(true);
  const [showFullReport, setShowFullReport] = useState(false);

  useEffect(() => {
    async function fetchValuation() {
      const { data, error } = await supabase
        .from('domain_valuations')
        .select('*')
        .eq('domain', domain)
        .single();

      if (!error && data?.valuation) {
        setValuation(data.valuation as DomainValuation);
      }
      setLoading(false);
    }

    fetchValuation();
  }, [domain]);

  if (loading) {
    return (
      <section className="mb-12">
        <h2 className="mb-6 text-3xl font-bold text-gray-900">AI Domain Valuation</h2>
        <div className="animate-pulse space-y-4">
          <div className="h-24 rounded-lg bg-gray-200"></div>
          <div className="grid gap-4 md:grid-cols-2">
            <div className="h-48 rounded-lg bg-gray-200"></div>
            <div className="h-48 rounded-lg bg-gray-200"></div>
          </div>
        </div>
      </section>
    );
  }

  if (!valuation) {
    return null;
  }

  return (
    <section className="mb-12">
      <h2 className="mb-6 text-3xl font-bold text-gray-900">AI Domain Valuation</h2>

      {/* Estimated Value */}
      <div className="mb-6 rounded-lg border-2 border-green-500 bg-gradient-to-r from-green-50 to-emerald-50 p-8 text-center">
        <p className="mb-2 text-sm font-semibold uppercase tracking-wide text-green-700">
          Estimated Market Value
        </p>
        <p className="text-4xl font-bold text-green-900">{valuation.estimated_value_range}</p>
        <p className="mt-2 text-xs text-gray-600">
          Generated by Grok AI • {new Date(valuation.generated_at).toLocaleDateString()}
        </p>
      </div>

      <div className="grid gap-6 md:grid-cols-2">
        {/* Key Strengths */}
        <div className="rounded-lg border border-gray-200 bg-white p-6">
          <h3 className="mb-4 flex items-center gap-2 text-lg font-semibold text-gray-900">
            <span className="text-2xl">💪</span>
            Key Strengths
          </h3>
          <ul className="space-y-2">
            {valuation.key_strengths.map((strength, idx) => (
              <li key={idx} className="flex items-start gap-2 text-sm text-gray-700">
                <span className="mt-1 text-green-600">✓</span>
                <span>{strength}</span>
              </li>
            ))}
          </ul>
        </div>

        {/* Competitive Advantages */}
        <div className="rounded-lg border border-gray-200 bg-white p-6">
          <h3 className="mb-4 flex items-center gap-2 text-lg font-semibold text-gray-900">
            <span className="text-2xl">🎯</span>
            Competitive Advantages
          </h3>
          <ul className="space-y-2">
            {valuation.competitive_advantages.map((advantage, idx) => (
              <li key={idx} className="flex items-start gap-2 text-sm text-gray-700">
                <span className="mt-1 text-blue-600">→</span>
                <span>{advantage}</span>
              </li>
            ))}
          </ul>
        </div>

        {/* Potential Use Cases */}
        <div className="rounded-lg border border-gray-200 bg-white p-6 md:col-span-2">
          <h3 className="mb-4 flex items-center gap-2 text-lg font-semibold text-gray-900">
            <span className="text-2xl">💡</span>
            Potential Use Cases
          </h3>
          <div className="grid gap-3 sm:grid-cols-2">
            {valuation.potential_use_cases.map((useCase, idx) => (
              <div
                key={idx}
                className="rounded-lg bg-purple-50 px-4 py-3 text-sm text-gray-800"
              >
                {useCase}
              </div>
            ))}
          </div>
        </div>

        {/* Monetization Opportunities */}
        <div className="rounded-lg border border-gray-200 bg-white p-6">
          <h3 className="mb-4 flex items-center gap-2 text-lg font-semibold text-gray-900">
            <span className="text-2xl">💰</span>
            Monetization Ideas
          </h3>
          <ul className="space-y-2">
            {valuation.monetization_opportunities.map((opportunity, idx) => (
              <li key={idx} className="flex items-start gap-2 text-sm text-gray-700">
                <span className="mt-1 text-green-600">$</span>
                <span>{opportunity}</span>
              </li>
            ))}
          </ul>
        </div>

        {/* Improvement Recommendations */}
        <div className="rounded-lg border border-gray-200 bg-white p-6">
          <h3 className="mb-4 flex items-center gap-2 text-lg font-semibold text-gray-900">
            <span className="text-2xl">📈</span>
            Growth Opportunities
          </h3>
          <ul className="space-y-2">
            {valuation.improvement_recommendations.map((rec, idx) => (
              <li key={idx} className="flex items-start gap-2 text-sm text-gray-700">
                <span className="mt-1 text-orange-600">⚡</span>
                <span>{rec}</span>
              </li>
            ))}
          </ul>
        </div>
      </div>

      {/* Market Analysis */}
      <div className="mt-6 rounded-lg border border-gray-200 bg-white p-6">
        <h3 className="mb-4 flex items-center gap-2 text-lg font-semibold text-gray-900">
          <span className="text-2xl">📊</span>
          Market Analysis
        </h3>
        <div className="prose prose-sm max-w-none text-gray-700">
          {valuation.market_analysis.split('\n\n').map((paragraph, idx) => (
            <p key={idx} className="mb-3">
              {paragraph}
            </p>
          ))}
        </div>
      </div>

      {/* Full Report Toggle */}
      <div className="mt-6 text-center">
        <button
          onClick={() => setShowFullReport(!showFullReport)}
          className="rounded-lg bg-gray-100 px-6 py-3 font-semibold text-gray-700 transition hover:bg-gray-200"
        >
          {showFullReport ? 'Hide' : 'Show'} Full Valuation Report
        </button>
      </div>

      {/* Full Report */}
      {showFullReport && (
        <div className="mt-6 rounded-lg border border-gray-200 bg-white p-8">
          <div
            className="prose prose-sm max-w-none"
            dangerouslySetInnerHTML={{
              __html: valuation.full_report
                .replace(/^### /gm, '<h3 class="text-xl font-bold mt-6 mb-3">')
                .replace(/^## /gm, '<h2 class="text-2xl font-bold mt-8 mb-4">')
                .replace(/^\*\*(.+?)\*\*/gm, '<strong>$1</strong>')
                .replace(/\n\n/g, '</p><p class="mb-3">')
                .replace(/^(.+)$/gm, '<p class="mb-3">$1</p>'),
            }}
          />
        </div>
      )}
    </section>
  );
}
