import Link from 'next/link';
import Image from 'next/image';
import type { Metadata } from 'next';
import SearchBar from '@/components/SearchBar';
import { seedTopics } from '@/lib/seed-topics';
import { slugify } from '@/lib/slugify';
import { LOGOS, LOGO_SIZES } from '@/lib/logos';

const siteUrl =
  process.env.NEXT_PUBLIC_SITE_URL ||
  (process.env.NODE_ENV === 'production' ? 'https://wikithat.com' : 'http://localhost:3000');

export const metadata: Metadata = {
  title: 'Wikithat - Compare Wikipedia vs Grokipedia Side-by-Side',
  description: 'Compare any topic side-by-side on Wikipedia and Grokipedia. See how traditional encyclopedia stacks up against AI-powered knowledge. Get AI-generated verdicts powered by Grok.',
  keywords: ['Wikipedia', 'Grokipedia', 'comparison', 'encyclopedia', 'AI knowledge', 'fact check', 'Grok AI', 'knowledge comparison', 'Wikipedia vs Grokipedia', 'Grokipedia accuracy'],
  alternates: {
    canonical: siteUrl,
  },
  openGraph: {
    title: 'Wikithat - Compare Wikipedia vs Grokipedia',
    description: 'Compare any topic side-by-side. Traditional encyclopedia vs AI-powered knowledge.',
    url: siteUrl,
    type: 'website',
    siteName: 'Wikithat',
    images: [
      {
        url: '/opengraph-image',
        width: 1200,
        height: 630,
        alt: 'Wikithat - Compare Wikipedia and Grokipedia',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Wikithat - Compare Wikipedia vs Grokipedia',
    description: 'Compare any topic side-by-side. Traditional encyclopedia vs AI-powered knowledge.',
    images: ['/opengraph-image'],
  },
};

export default function HomePage() {
  // Structured data for homepage
  const structuredData = {
    '@context': 'https://schema.org',
    '@type': 'WebSite',
    name: 'Wikithat',
    alternateName: 'WikiThat - Wikipedia vs Grokipedia Comparison',
    url: siteUrl,
    description: 'Compare Wikipedia and Grokipedia articles side-by-side. A free comparison tool for encyclopedia content across traditional and AI-powered knowledge sources.',
    about: {
      '@type': 'Thing',
      name: 'Knowledge Comparison Tool',
      description: 'Tool for comparing Wikipedia and Grokipedia encyclopedia articles',
    },
    audience: {
      '@type': 'Audience',
      audienceType: 'Researchers, Students, Fact-checkers, Knowledge Seekers',
    },
    potentialAction: {
      '@type': 'SearchAction',
      target: {
        '@type': 'EntryPoint',
        urlTemplate: `${siteUrl}/compare/{search_term_string}`,
      },
      'query-input': 'required name=search_term_string',
    },
    publisher: {
      '@type': 'Organization',
      name: 'Wikithat',
      url: siteUrl,
      description: 'Free tool to compare Wikipedia and Grokipedia side-by-side',
    },
  };

  const faqStructuredData = {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: [
      {
        '@type': 'Question',
        name: 'What is Wikithat?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'Wikithat is a free comparison tool that displays Wikipedia and Grokipedia articles side-by-side, so you can see how a traditional, community-edited encyclopedia differs from an AI-powered knowledge source built by xAI.',
        },
      },
      {
        '@type': 'Question',
        name: 'What is Grokipedia?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'Grokipedia is an AI-generated encyclopedia launched by xAI (Elon Musk\'s AI company) in October 2025. Unlike Wikipedia, which is written and edited by human volunteers, Grokipedia articles are generated by the Grok large language model. This creates notable differences in tone, coverage, and sometimes factual accuracy.',
        },
      },
      {
        '@type': 'Question',
        name: 'How does Wikithat work?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'Search for any topic and Wikithat fetches the corresponding articles from both Wikipedia and Grokipedia. The summaries are displayed side-by-side so you can compare them directly. An AI-generated verdict highlights key differences, and you can vote on which source you trust more.',
        },
      },
      {
        '@type': 'Question',
        name: 'Is Grokipedia more accurate than Wikipedia?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'It depends on the topic. Wikipedia benefits from decades of community editing and sourced citations. Grokipedia offers AI-generated summaries that can be more concise but sometimes contain inaccuracies or reflect training data biases. Wikithat lets you compare both and decide for yourself.',
        },
      },
      {
        '@type': 'Question',
        name: 'Is Wikithat affiliated with Wikipedia or Grokipedia?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'No. Wikithat is an independent comparison tool and is not affiliated with, endorsed by, or connected to the Wikimedia Foundation (Wikipedia) or xAI (Grokipedia).',
        },
      },
    ],
  };

  return (
    <main className="container mx-auto px-4 py-16">
      {/* Structured Data */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqStructuredData) }}
      />

      {/* Hero Section */}
      <div className="mb-12 text-center">
        <h1 className="mb-4 text-5xl font-bold">
          <span className="text-blue-600">Wikipedia</span> vs{' '}
          <span className="text-purple-600">Grokipedia</span>
        </h1>
        <p className="mb-8 text-xl text-gray-600">
          Compare any topic side-by-side and see the difference
        </p>

        <div className="flex justify-center">
          <SearchBar />
        </div>
      </div>

      {/* SEO Intro Copy */}
      <section className="mb-16 max-w-3xl mx-auto">
        <p className="text-gray-700 text-lg leading-relaxed mb-4">
          Since Grokipedia launched in October 2025, millions of people have wondered: how does an AI-written
          encyclopedia compare to Wikipedia, the world&apos;s largest human-edited knowledge base?
          <strong> Wikithat answers that question</strong> by placing both sources side-by-side for any topic you choose.
        </p>
        <p className="text-gray-700 leading-relaxed mb-4">
          Wikipedia articles are written and reviewed by a global community of volunteers, backed by citations and editorial
          policies developed over two decades. Grokipedia, built by Elon Musk&apos;s xAI, generates its articles using the Grok
          large language model &mdash; offering a different perspective that can be more concise but sometimes
          reflects the biases and limitations of AI-generated content.
        </p>
        <p className="text-gray-700 leading-relaxed">
          Whether you&apos;re a student fact-checking a research paper, a journalist verifying sources, or simply
          curious about how AI rewrites human knowledge &mdash; Wikithat gives you the tools to compare,
          vote, and decide for yourself which source you trust more.
        </p>
      </section>

      {/* Popular Comparisons */}
      <section className="mt-16">
        <h2 className="mb-6 text-center text-2xl font-bold">
          Popular Comparisons
        </h2>
        <div className="grid gap-4 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">
          {seedTopics.slice(0, 12).map((topic) => (
            <Link
              key={topic}
              href={`/compare/${slugify(topic)}`}
              className="group rounded-lg border border-gray-300 bg-white p-4 transition hover:border-blue-500 hover:shadow-md"
            >
              <div className="mb-3 flex items-center justify-center gap-2">
                <Image
                  src={LOGOS.wikipedia.icon}
                  alt="Wikipedia"
                  width={LOGO_SIZES.iconSmall.width}
                  height={LOGO_SIZES.iconSmall.height}
                  className="object-contain opacity-70 group-hover:opacity-100 transition-opacity"
                />
                <span className="text-gray-400">vs</span>
                <Image
                  src={LOGOS.grokipedia.icon}
                  alt="Grokipedia"
                  width={LOGO_SIZES.iconSmall.width}
                  height={LOGO_SIZES.iconSmall.height}
                  className="object-contain opacity-70 group-hover:opacity-100 transition-opacity"
                />
              </div>
              <div className="text-center font-semibold text-gray-900">
                {topic}
              </div>
            </Link>
          ))}
        </div>
      </section>

      {/* How It Works */}
      <section className="mt-16 rounded-lg bg-gradient-to-r from-blue-100 to-purple-100 p-8">
        <h2 className="mb-4 text-center text-2xl font-bold">How It Works</h2>
        <div className="grid gap-6 md:grid-cols-3">
          <div className="text-center">
            <div className="mb-2 text-4xl">🔍</div>
            <h3 className="mb-2 font-semibold">Search</h3>
            <p className="text-gray-700">
              Enter any topic you want to compare
            </p>
          </div>
          <div className="text-center">
            <div className="mb-2 text-4xl">⚖️</div>
            <h3 className="mb-2 font-semibold">Compare</h3>
            <p className="text-gray-700">
              See Wikipedia and Grokipedia side-by-side
            </p>
          </div>
          <div className="text-center">
            <div className="mb-2 text-4xl">🗳️</div>
            <h3 className="mb-2 font-semibold">Vote</h3>
            <p className="text-gray-700">Share which source you trust more</p>
          </div>
        </div>
      </section>

      {/* Visible FAQ Section */}
      <section className="mt-16 max-w-3xl mx-auto">
        <h2 className="mb-8 text-center text-2xl font-bold">
          Frequently Asked Questions
        </h2>
        <div className="space-y-6">
          <details className="rounded-lg border border-gray-200 bg-white p-4" open>
            <summary className="cursor-pointer font-semibold text-gray-900">
              What is Wikithat?
            </summary>
            <p className="mt-3 text-gray-700">
              Wikithat is a free comparison tool that displays Wikipedia and Grokipedia articles
              side-by-side, so you can see how a traditional, community-edited encyclopedia differs
              from an AI-powered knowledge source built by xAI.
            </p>
          </details>

          <details className="rounded-lg border border-gray-200 bg-white p-4">
            <summary className="cursor-pointer font-semibold text-gray-900">
              What is Grokipedia?
            </summary>
            <p className="mt-3 text-gray-700">
              Grokipedia is an AI-generated encyclopedia launched by xAI (Elon Musk&apos;s AI company)
              in October 2025. Unlike Wikipedia, which is written and edited by human volunteers,
              Grokipedia articles are generated by the Grok large language model. This creates notable
              differences in tone, coverage, and sometimes factual accuracy.
            </p>
          </details>

          <details className="rounded-lg border border-gray-200 bg-white p-4">
            <summary className="cursor-pointer font-semibold text-gray-900">
              How does Wikithat work?
            </summary>
            <p className="mt-3 text-gray-700">
              Search for any topic and Wikithat fetches the corresponding articles from both Wikipedia
              and Grokipedia. The summaries are displayed side-by-side so you can compare them directly.
              An AI-generated verdict highlights key differences, and you can vote on which source you
              trust more.
            </p>
          </details>

          <details className="rounded-lg border border-gray-200 bg-white p-4">
            <summary className="cursor-pointer font-semibold text-gray-900">
              Is Grokipedia more accurate than Wikipedia?
            </summary>
            <p className="mt-3 text-gray-700">
              It depends on the topic. Wikipedia benefits from decades of community editing and sourced
              citations. Grokipedia offers AI-generated summaries that can be more concise but sometimes
              contain inaccuracies or reflect training data biases. Wikithat lets you compare both and
              decide for yourself.
            </p>
          </details>

          <details className="rounded-lg border border-gray-200 bg-white p-4">
            <summary className="cursor-pointer font-semibold text-gray-900">
              Is Wikithat affiliated with Wikipedia or Grokipedia?
            </summary>
            <p className="mt-3 text-gray-700">
              No. Wikithat is an independent comparison tool and is not affiliated with, endorsed by,
              or connected to the Wikimedia Foundation (Wikipedia) or xAI (Grokipedia).
            </p>
          </details>
        </div>
      </section>

      {/* Topic Categories */}
      <section className="mt-16">
        <h2 className="mb-6 text-center text-2xl font-bold">
          Browse by Category
        </h2>
        <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
          <Link
            href="/topics/politics"
            className="rounded-lg border border-gray-200 bg-white p-6 transition hover:border-blue-500 hover:shadow-md"
          >
            <h3 className="font-bold text-lg text-gray-900 mb-1">Politics</h3>
            <p className="text-sm text-gray-600">Trump, Biden, Ukraine & more</p>
          </Link>
          <Link
            href="/topics/technology"
            className="rounded-lg border border-gray-200 bg-white p-6 transition hover:border-blue-500 hover:shadow-md"
          >
            <h3 className="font-bold text-lg text-gray-900 mb-1">Technology</h3>
            <p className="text-sm text-gray-600">AI, ChatGPT, Cybersecurity & more</p>
          </Link>
          <Link
            href="/topics/science"
            className="rounded-lg border border-gray-200 bg-white p-6 transition hover:border-blue-500 hover:shadow-md"
          >
            <h3 className="font-bold text-lg text-gray-900 mb-1">Science</h3>
            <p className="text-sm text-gray-600">Climate, Space, Gene Editing & more</p>
          </Link>
          <Link
            href="/topics/crypto-finance"
            className="rounded-lg border border-gray-200 bg-white p-6 transition hover:border-blue-500 hover:shadow-md"
          >
            <h3 className="font-bold text-lg text-gray-900 mb-1">Crypto & Finance</h3>
            <p className="text-sm text-gray-600">Bitcoin, Blockchain, NFT & more</p>
          </Link>
          <Link
            href="/topics/business"
            className="rounded-lg border border-gray-200 bg-white p-6 transition hover:border-blue-500 hover:shadow-md"
          >
            <h3 className="font-bold text-lg text-gray-900 mb-1">Business & Innovation</h3>
            <p className="text-sm text-gray-600">SpaceX, Tesla, EVs & more</p>
          </Link>
        </div>
      </section>
    </main>
  );
}
