import Link from 'next/link';
import type { Metadata } from 'next';

const siteUrl =
  process.env.NEXT_PUBLIC_SITE_URL ||
  (process.env.NODE_ENV === 'production' ? 'https://wikithat.com' : 'http://localhost:3000');

export const metadata: Metadata = {
  title: 'Terms of Service',
  description: 'Terms of service for Wikithat.com. Read our terms and conditions for using the Wikipedia vs Grokipedia comparison tool.',
  alternates: {
    canonical: `${siteUrl}/terms`,
  },
};

export default function TermsPage() {
  return (
    <main className="container mx-auto px-4 py-16 max-w-3xl">
      <h1 className="mb-8 text-4xl font-bold">Terms of Service</h1>
      <p className="mb-6 text-sm text-gray-500">Last updated: February 26, 2026</p>

      <div className="prose prose-lg max-w-none space-y-6 text-gray-700">
        <h2 className="text-2xl font-bold mt-8 mb-4">Acceptance of Terms</h2>
        <p className="leading-relaxed">
          By accessing and using Wikithat (&ldquo;the Service&rdquo;), available at wikithat.com,
          you agree to be bound by these Terms of Service. If you do not agree to these terms,
          please do not use the Service.
        </p>

        <h2 className="text-2xl font-bold mt-8 mb-4">Description of Service</h2>
        <p className="leading-relaxed">
          Wikithat is a free comparison tool that displays Wikipedia and Grokipedia articles
          side-by-side. The Service fetches content from Wikipedia (via its public API) and
          Grokipedia (via web scraping) and presents it for comparison purposes.
        </p>

        <h2 className="text-2xl font-bold mt-8 mb-4">Content Disclaimer</h2>
        <p className="leading-relaxed">
          Wikithat does not create, edit, or endorse the content displayed from Wikipedia or
          Grokipedia. All article content is owned by and sourced from their respective platforms:
        </p>
        <ul className="list-disc pl-6 space-y-1">
          <li><strong>Wikipedia content</strong> is licensed under the Creative Commons Attribution-ShareAlike License (CC BY-SA) by the Wikimedia Foundation</li>
          <li><strong>Grokipedia content</strong> is generated by xAI and subject to their terms of use</li>
          <li><strong>AI-generated verdicts</strong> are produced by the Grok AI model and should not be treated as factual analysis</li>
        </ul>

        <h2 className="text-2xl font-bold mt-8 mb-4">Accuracy and Reliability</h2>
        <p className="leading-relaxed">
          Wikithat makes no guarantees about the accuracy, completeness, or reliability of any
          content displayed through the Service. Content from both Wikipedia and Grokipedia may
          contain errors, biases, or outdated information. Users should independently verify any
          information before relying on it.
        </p>

        <h2 className="text-2xl font-bold mt-8 mb-4">Acceptable Use</h2>
        <p className="leading-relaxed">
          You agree not to:
        </p>
        <ul className="list-disc pl-6 space-y-1">
          <li>Use the Service for any unlawful purpose</li>
          <li>Attempt to overload, disrupt, or interfere with the Service</li>
          <li>Scrape or bulk-download content from the Service</li>
          <li>Use automated tools to access the Service beyond normal browsing</li>
          <li>Misrepresent Wikithat content as original content from Wikipedia or Grokipedia</li>
        </ul>

        <h2 className="text-2xl font-bold mt-8 mb-4">Intellectual Property</h2>
        <p className="leading-relaxed">
          The Wikithat name, logo, website design, and comparison tool software are the property of
          Wikithat. The comparison interface, voting system, and AI verdict features are original
          to Wikithat. Third-party content (Wikipedia articles, Grokipedia articles) remains the
          property of their respective owners.
        </p>

        <h2 className="text-2xl font-bold mt-8 mb-4">Limitation of Liability</h2>
        <p className="leading-relaxed">
          Wikithat is provided &ldquo;as is&rdquo; without warranty of any kind, express or implied.
          In no event shall Wikithat be liable for any indirect, incidental, special, consequential,
          or punitive damages arising from your use of the Service.
        </p>

        <h2 className="text-2xl font-bold mt-8 mb-4">Changes to Terms</h2>
        <p className="leading-relaxed">
          We reserve the right to modify these Terms of Service at any time. Changes will be posted
          on this page with an updated revision date. Continued use of the Service after changes
          constitutes acceptance of the modified terms.
        </p>

        <h2 className="text-2xl font-bold mt-8 mb-4">Contact</h2>
        <p className="leading-relaxed">
          For questions about these Terms of Service, contact us at <strong>hello@wikithat.com</strong>.
        </p>
      </div>

      <div className="mt-12">
        <Link href="/" className="text-blue-600 hover:underline">
          &larr; Back to comparisons
        </Link>
      </div>
    </main>
  );
}
