export const seedTopics = [
  'Elon Musk',
  'Bitcoin',
  'Artificial Intelligence',
  'Donald Trump',
  'Climate Change',
  'COVID-19',
  'SpaceX',
  'Tesla',
  'ChatGPT',
  'Quantum Computing',
  'Joe Biden',
  'Ukraine',
  'Palestine',
  'iPhone',
  'Mars',
  'Nuclear Energy',
  'Web3',
  'Blockchain',
  'Virtual Reality',
  'Social Media',
  'Renewable Energy',
  'Electric Vehicles',
  'Cryptocurrency',
  'Machine Learning',
  'Metaverse',
  'NFT',
  'Autonomous Vehicles',
  'Gene Editing',
  'Space Exploration',
  'Cybersecurity',
];
